# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52aa5ba6d6dbc620ffaa774a80bf4b3b56c8590d588f63b39c266c6190c4c8376f4f65377b1345c3bb331bb50dde18eab94a2fd50dc765500c99e5a2b541cc4d

test:
  secret_key_base: 14957c79124394f0666a6102d66a9a562557f95bcca03c0e4663adb5f3217fe43854f2bd90a8efe7127e4c5625843ec167e9e460e91939625ced6c7c77102645

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
